---
abstract: 'Munge scalars, hashes and arrays in flexible ways'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Differences: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101582, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-SmartMunge
provides:
  Data::SmartMunge:
    file: lib/Data/SmartMunge.pm
    version: 1.101610
requires:
  Exporter: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-SmartMunge
  homepage: http://search.cpan.org/dist/Data-SmartMunge/
  repository: http://github.com/hanekomu/Data-SmartMunge
version: 1.101610
